### ISSUE TITLE
No sound in pspemu

### ISSUE THREAD

**Issue by Rufis01** [TheOfficialFloW/Adrenaline#11]
If you go to livearea when you play a ps1 game, reopen adrenaline, and then return to xmb, there is no sound. If you go to livearea again and reopen adrenaline the sound works again.

**Comment by TheOfficialFloW** [comment]
Not a big deal.

**Comment by TheOfficialFloW** [comment]
Fixed https://github.com/TheOfficialFloW/Adrenaline/commit/6fd9286653e297a64164e302764af02941cec79e

**Comment by kamilb880** [comment]
Issue is still visible, don't know if it is the same, or caused by some other bug. Steps to reproduce:

- go to Adrenaline, sound is present (menu & on previewing PSP images)
- start PS1 game
- after some time press PS button and go back to Adrenaline's XMB

Sound is gone. Restarting Adrenaline fixes the problem, also putting Vita into standby mode and then waking it up fixes issue. Yet then battery in Adrenaline's XMB is showing like it is charging (Vita unplugged). Also standby mode fixes issue.

Issue spotted while launching & exiting MGS and Silent Hill 
Appearance: 70-80% tries
