### ISSUE TITLE
Adrenaline isn't able to use ISO files with names longer than 64 chars

### ISSUE THREAD

**Issue by Florin9doi** [TheOfficialFloW/Adrenaline#111]
Short story: Adrenaline isn't able to use ISO files with names longer than 64 chars. When used, those files doesn't appear in XMB. 

Not-so-long story: Some people prefer to keep the games using No-Intro name conventions. Those files can have long names; (eg: _Grand Theft Auto - Liberty City Stories (Europe) (En,Fr,De,Es,It) (v3.00).iso_). Although they works without problems on a real PSP, those files do not appears in Adrenaline unless the names are cut under 64 chars: (eg: _Grand Theft Auto - Liberty City Stories (Europe) (E(v3.00).iso_). 
Would be nice to be able to drop the files without renaming them.

**Comment by dude22072** [comment]
Whats the problem with renaming files? Do you _need_ to know it's a European Iso? Do you _need_ to know it's in the 5 languages most European games are in? Do you _need_ to know it's v3? It seems like you're asking for a solution to an avoidable problem.

**Comment by TheOfficialFloW** [comment]
Should be fixed in the next update https://github.com/TheOfficialFloW/Adrenaline/commit/f4c394f8f70fa8b4d50d26df1b93edcb968d38b3

**Comment by Florin9doi** [comment]
I've built the latest version, but this issue is still present. 
It's the same even after increasing
```
cef/vshctrl/isofs_driver/umd9660_driver.c:umdfilename and
cef/vshctrl/virtualpbpmgr.h:VirtualPbp:isofile
```
Do you have other idea?
