### ISSUE TITLE
ADRENALINE Wont start.

### ISSUE THREAD

**Issue by aleexiisz57** [TheOfficialFloW/Adrenaline#135]
I have just tried to install adrenaline VPK and everything seems to run smooth until i have to start adrenaline and then it just gets stuck on the "playstation portable" screen and after a while i get the error "C1-2858-3". I cant seem to fully run adrenaline even though i deleted the ux0:/adrenaline on vitashell. also my vita is not activated but i don't think thats the problem. if you need additional information let me know. I can't even start adrenaline but thanks for working on it.
SCREENSHOT OF SCREEN
![2017-09-04-191121](https://user-images.githubusercontent.com/11556392/30040619-a5ec3036-9196-11e7-81df-8ba3b629fce5.jpg)

**Comment by TheRadziu** [comment]
You probably have some plugins in `*ALL` , exclude adrenaline from ALL list and it should be working

**Comment by aleexiisz57** [comment]
@TheRadziu I tried disabling it and is disabled but it still wont start, maybe if i delete everything and format my card it'll work but it'll be nice to know why the it won't start and i get this screen that i didn't see in a video on youtube on how to install it. Thanks for you help

https://www.youtube.com/watch?v=DWuNoyJoMgM&t=379s

**Comment by TheRadziu** [comment]
Now, once you edited your issue with screenshot, it doesnt look right at all.
reinstall vpk (make sure ux0:/app/PSPEMUCFW folder is gone after you done that), make sure your config.txt doesnt have any traces of old adrenaline and remove ux0:/adrenaline if present. 
Also make sure ux0:/pspemu/seplugins folder is empty. 

Everything I just listed (excluding full vpk reinstall) is related if you had adrenaline 5.1 or lower installed before. From the screenshot/picture it looks like corrupted/modded f0 ?

**Comment by aleexiisz57** [comment]
Okay i found the problem. I downloaded and installed this plugin pack https://www.reddit.com/r/vitahacks/comments/6hyo42/release_adrenaline_ecfw_plugins_utilities_pack/
i guess the new adrenaline.vpk is not compatible with the plugins i had so before adrenaline booted i press the R bottom to recovery and disabled every single plugin and then it booted normally. Also by mistake i try to open ARK and it works even though like i said earlier my vita is not activated. thanks for the help and i will try to see which plugins i can enable without getting stuck on the boot screen

**Comment by slick915** [comment]
i was able to fix it by erasing the adrenaline forlder on ux0: and then i erased the pspemu folder on ux0. after, imade a new folder and names it pspemu on the ux0 folder and then made another folder insidide pspemu foldder and named it seplugins then i just ran the adrenaline vpk normaly and then it finally worked!
